### ISSUE TITLE
4 Player Doesn't work on one PC

### ISSUE THREAD

**Issue by Sb8808** [Tacitor/ICS4U-Settlers-Of-Catan#155]
**Describe the bug**
When loading a 4 person server on one computer, using 4 different instances of the game, booting the game up and connecting one at a time, only 3 of the 4 game instances and connect to the localhost. Additionally, after joining, the instance of the game closes, but still registers in the server as a player. It is currently unclear whether a 4th player (which can't join) will bring back the original instances.

When doing this with a 3 player game, all instances connect.
**To Reproduce**
Start a 4 player game in online mode, Starting resources: Yes, Snake Rules: Yes, Limit Game Pieces: 15 Roads, 5 Settlements, 4 Cities, and Click Start game. Click Start Server.
 Open up another instance of the game using the same download. Click "Join an Online Game" and then connect to localhost on port 25570. Choose White
Do the previous step again. Instead, choose blue
Both instances of the game should close automatically (not sure if this is bug)
Now, attempt to connect a 4th instance of the game. Should say "Failed (1)! Try Again".

**Expected behavior**
First, the other two instances should not be disappearing.
The 4th instance should be able to join because of the 4 player game while only 3 are in the game session.
**Screenshots**
![image](https://github.com/Tacitor/ICS4U-Settlers-Of-Catan/assets/149029957/63320da7-b0f6-415e-8648-3ab151fac933)

**Comment by Tacitor** [comment]
I will look into this. Thank you.

**Comment by Tacitor** [comment]
Also related to this is #156

**Comment by Tacitor** [comment]
![image](https://github.com/Tacitor/ICS4U-Settlers-Of-Catan/assets/71619334/a4f00a6c-147e-4619-bcf6-e1be844acdca)

Cannot reproduce, works fine when following your provided steps. Can you try again to see if it works?
