### ISSUE TITLE
Add Mr. Cuttens requirements

### ISSUE THREAD

**Issue by Tacitor** [Tacitor/ICS4U-Settlers-Of-Catan#46]
Working
-set up phase, good error messages
-overall look and feel
-buying and placing roads, settlements, cities
-game win
-game stats

Missing features
-build requirements (distance, attachment to roads) ✅
-alternating setup ✅
-start up resources ✅
-turn indicator ✅
-losing 1/2 resources when 7 is rolled ✅

Bugs
-can't load? ✅
-cards get cut off when there are too many ✅

Next
-grey out buttons when they can't be clicked ✅

**Comment by Evan-Kreutzwiser** [comment]
Start up resources and disabling build buttons based on the player's cards has been added

**Comment by Tacitor** [comment]
> Start up resources and disabling build buttons based on the player's cards has been added

Feel free to make new issues for those and mark them as resolved. I ~~pretty much~~ just dumped this here.

**Comment by Tacitor** [comment]
All done
